### ISSUE TITLE
Fix JSHint issues

### ISSUE THREAD

**Issue by sgoumaz** [pryv/bridge-twitter#4] opened 2014-02-27 19:00 UTC
All source and test files must pass (I did some fixes today but there's a lot remaining). If not done already check the available editor plugins (eg. for Sublime): http://www.jshint.com/install/

**Comment by kschiess** [comment] 2017-08-30 11:26
Closing Unresolved: We've moved to eslint  - and fixing warnings is one of our daily occupations. This is not a bug we can fix once and for all, but rather an ongoing practice.

**Closed by kschiess** 2017-08-30 11:26 UTC
